### ISSUE TITLE
Adding detrending/drift removal functionality

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#123]
I have developed quite a bit of logic to remove control run drift from CMIP6 models for my recent [OMZ paper](https://www.essoar.org/doi/10.1002/essoar.10507050.1), and would like to refactor this into cmip6_preprocessing.

The logic I use has these basic steps:

- Use the metadata of every historical member (see #95 for further explanation of nomenclature) to get the branch time in the parent `piControl` run `branch_time_parent`.
- Select a 250 year time period starting at `branch_time_parent`, and calculate a linear slope at every `x`, `y`, and `lev` position. Save that output
- Remove this trend from historical and forced runs by assuming an intercept of 0 at time `1850-01-01` (the time when the historical forcing starts). 

I will migrate this functionality here (and would then welcome feedback), but I wanted to discuss the API first.

First of all I was wondering about how to call the module (which I would create for this purpose): 
- `cmip6_preprocessing/drift_correction`
- `cmip6_preprocessing/time_tools` (this could more general time related functionality like #64, which is also needed for the above tools)
- `cmip6_preprocessing/detrending` (seems a bit ambiguous to me?)
Not super stoked about these yet. Any ideas?

For the API I would imagine something along the lines of:
```python
from cmip6_preprocessing.cool_modulename import sel_from_branch, detrend

ds = ...
ds_control ... # matching control run (can be inferred and matched from attributes similar as in #120)

matching_control = sel_from_branch(ds, ds_control, yrs=250)
slope = matching_control.polyfit(dim='time', deg=1)
# in a realistic workflow I would save these files out (they are relatively small) and load them back for analysis
ds_nodrift = detrend(ds, slope, start_date = '1850-01-01`)
```

Any thoughts?

cc @MackenzieBlanusa

**Comment by MackenzieBlanusa** [comment]
For a module name, I think `cmip6_preprocessing/drift_correction` is a good choice. The API is nice and straightforward. I'm a little confused on matching the control run. Do you match the control run with historical members?

**Comment by jbusecke** [comment]
Thanks for the feedback @MackenzieBlanusa. Yes my approach is to find the time where the 'historical' run was split from 'piControl', the 250 year linear trend should then be applicable to any combination of 'historical' and scenarios. 
This makes sure that we only suptract a single linear trend. 

I am not sure if one can make an argument to detrend the scenarios separately, but in that case I would be worried that the different duration could lead to spurious signals due to interannual-decdal variability in the control.

What do you think?

**Comment by MackenzieBlanusa** [comment]
Thanks for the clarification @jbusecke. I agree with your concern about detrending the scenarios separately. I think it would be best to just work with the single linear trend obtained from the historical and piControl.

**Comment by jbusecke** [comment]
Ill try to start working on this today, and will ping you here once I have a working PR.
