### ISSUE TITLE
merge_variables giving error: Unrecognised value for combine_attrs=drop_conflicts

### ISSUE THREAD

**Issue by Recalculate** [jbusecke/cmip6_preprocessing#169]
The code given in the cmip6_postprocessing tutorial fails for me at the moment.  

`!pip install git+https://github.com/jbusecke/cmip6_preprocessing.git

# lets start by loading a few example dataset
from cmip6_preprocessing.utils import google_cmip_col
from cmip6_preprocessing.preprocessing import combined_preprocessing

col = google_cmip_col()
experiment_id='historical'
source_id = ['CanESM5-CanOE', 'GFDL-ESM4']
kwargs = {
    'zarr_kwargs':{
        'consolidated':True,
        'use_cftime':True
    },
    'aggregate':False,
    'preprocess':combined_preprocessing
}

cat_data = col.search(
    source_id=source_id,
    experiment_id=experiment_id,
    grid_label='gn',
    variable_id=['tos', 'zos']
)
ddict = cat_data.to_dataset_dict(**kwargs)
list(ddict.keys())`

Works just fine.  But when we come to combine the variables in the next cell:

`from cmip6_preprocessing.postprocessing import merge_variables

ddict_merged = merge_variables(ddict)
list(ddict_merged.keys())`

This returns an empty dict and gives the warnings: 

/srv/conda/envs/notebook/lib/python3.8/site-packages/cmip6_preprocessing/postprocessing.py:122: UserWarning: CMIP.NOAA-GFDL.GFDL-ESM4.historical.r1i1p1f1.Omon.gn.none failed to combine with :Unrecognised value for combine_attrs=drop_conflicts

For each file.   

I'm not sure why this is happening?  Possibly a change in the source code I'm importing?

**Comment by jbusecke** [comment]
Thanks for raising this issue. This is mostl likely due to your xarray version (which does not support the option `drop_conflicts`). Could you try to update xarray to the newest version and try again? I will need to refine the dependencies, I believe.

**Comment by Recalculate** [comment]
Thanks, that did it.

**Comment by jbusecke** [comment]
Awesome. I am going to fix the requirements in #170, and will close this here if that is ok?

**Comment by Recalculate** [comment]
Good for me.  I seem to be getting server resets when running concat_members now, but I expect that is a memory issue, I'm using a small node.  

More annoying, and very common, is running into time dimension missmatches constantly when running match_metrics.  Eg 

ScenarioMIP.CSIRO.ACCESS-ESM1-5.ssp585.r1i1p1f1.Omon.gn.v20210318:`metric` dimensions ['time:1032'] do not match `ds` ['time:2040'].

Is there any way to get it to ignore these (or will it cause an issue later anyway when trying to merge?).  Presumably the only way to avoid it is to hunt down every single model/member in a for loop of doom?
