### ISSUE TITLE
xarray 0.19.0 breaks cmip6_preprocessing

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#173]
Our CI is currently [broken](https://github.com/jbusecke/cmip6_preprocessing/actions). I supect the new xarray release. 
Will investigate now.

**Comment by dcherian** [comment]
should add an "upstream" test environment to avoid this kind of thing

**Comment by jbusecke** [comment]
I do have one...but I must have been to aggressive with turning off notifications?

**Comment by jbusecke** [comment]
Is there a way to get an email notification ONLY if the scheduled CI fails?
