### ISSUE TITLE
Drop coordinate values of bound and vertex dimensions?

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#176]
I ran into some trouble with concating/mergin datasets that had different values for e.g. `bnds`. Some datasets do have a different datatype (int vs float) and then others use a [1,2] convention instead of [0,1]. 

I think we can just add 
```python
ds = ds.drop({d for d in ['bnds', 'verticies'] if d in ds.dims})
```
to the `combined_preprocessing` without loosing functionality? Or am I missing an important use case from anyone? 

cc @dcherian

**Comment by dcherian** [comment]
Sounds fine to me. What are the float values: `0.0, 1.0`?

**Comment by jbusecke** [comment]
I have found several `array([1., 2.]),` ones in there...damn you MATLAB!
