### ISSUE TITLE
Upstream Dev Build failing

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#179]
The upstream build is failing because it installs an older `regionmask` version...

How is the pip install straight from github not getting the latest updates?

I can reproduce the same behavior locally. If I do:
```
pip install git+https://github.com/mathause/regionmask.git
```

I get
```
python -c "import regionmask;print(regionmask.__version__)"
```
`0.6.2+dev`.

That seems bizarre to me. Maybe @mathause has an idea?

Ill switch to the conda install (which resolves to 0.7.0 🤔).

**Comment by mathause** [comment]
Ahh I got it - the repo was moved to it's own organization ([regionmask/regionmask](https://github.com/regionmask/regionmask)). Now my "fork" is at ([mathause/regionmask](https://github.com/mathause/regionmask)) which was lagging (I now pushed to it). You have to do:

```bash
pip install git+https://github.com/regionmask/regionmask.git

```

**Comment by jbusecke** [comment]
Thank you soo much @mathause, I totally did not catch that.
