### ISSUE TITLE
Add dummy naming scheme for AWI model

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#2]
There is no key in the renaming dict for the AWI model, resulting in an error. 

I should add at least an empty dummy entry to avoid this.

**Comment by andersy005** [comment]
First, I just want to say that after this is an amazing tool. Glad to see how nicely this tool integrates with intake-esm. Thank you for putting it together! I am planning on testing it on Cheyenne in the coming days. 


From a user perspective, I was wondering if it is worth moving the `dim_name_dict` into a YAML or JSON config file (persisted outside the package (`~/config/cmip6_preprocessing.yaml`) maybe? or some other location) that gets read by the package?
https://github.com/jbusecke/cmip6_preprocessing/blob/bcc9c108ecae72a8460f012b37756af691cd2985/cmip6_preprocessing/preprocessing.py#L196-L200

Having the content of the dictionary in a config file would probably make it easy for the user to extend the dictionary for their own use cases without needing to make changes in the code base itself. Thoughts?

**Comment by jbusecke** [comment]
Thanks for the kind words @andersy005. That is a great suggestion. 

I agree that a yaml would be easier to handle, but my initial hope was that we could build a comprehensive database of all the 'quirks` in CMIP6 over time, so eventually the user does not have to configure this anymore (thus I would store it in the package.

What would be the use-case for a user-customized file in your opinion?

**Comment by jbusecke** [comment]
Just picking back up on this. How about we have a 'built in' database (cmip6), but then we could check for another file in the user directory and overwrite the existing one? 
I am not that familiar with handling yaml files, but there must be an easy way to parse to a dict, right?

**Comment by jbusecke** [comment]
I have recently changed the way we use the internal renaming to a universal renaming dictionary. This is easier to manage, but perhaps it would still be good to be able to add additional dimension/coordinate names on the fly. I would like to move the further discussion about this to #52.
