### ISSUE TITLE
Attribute error thrown by cmip6_preprocessing.calculate_drift()

### ISSUE THREAD

**Issue by BWBlack** [jbusecke/cmip6_preprocessing#201]
Hi all,

I was surprised by this error recently, I haven't looked in to it in any depth yet but I though someone might have an idea of what's going on.

**The error:**

`AttributeError                            Traceback (most recent call last)`
`<timed exec> in <module>`

`~\Anaconda3\envs\CMIP6_field_analysis_env\lib\site-packages\cmip6_preprocessing\drift_removal.py in calculate_drift(reference, ``ds, variable, trend_years, compute_short_trends)`
`    196         ds.attrs["branch_time_in_parent"],`
`    197         ds.attrs["parent_time_units"],`
`--> 198         reference.time.to_index().calendar,`
`    199     )`
`    200     branch_idx_reference = find_date_idx(reference.time, branch_time_reference)`

`AttributeError: 'DatetimeIndex' object has no attribute 'calendar'`

**The code:**
Nothing unusual, just 
`%%time`
`drift = calculate_drift(picontrol, hist_r1, 'thetao')`
`drift = drift.load() `

**The data:**
MPIESM1.2 HR output - as above, a historical and PI output. I can provide the files if anyone would like them, but these are just what's available through CEDA
thetao_Omon_MPI-ESM1-2-HR_historical_r1i1p1f1_gn_185001-185412.nc
thetao_Omon_MPI-ESM1-2-HR_piControl_r1i1p1f1_gn_185001-185412.nc

This looks like its something to do with pandas, but maybe this can be avoided by changing time to some other format, at the moment
`type(picontrol.time.to_index()[0])`
`pandas._libs.tslibs.timestamps.Timestamp`

Thanks!

**Comment by jbusecke** [comment]
Hi @BWBlack, thank you so much for using cmip6_preprocessing and apologies for the long answering delay. 

I suspect that you are not decoding the times as cftime? This is required for this functionality to work. Could you confirm the datatype of the time coordinates?

**Comment by BWBlack** [comment]
Cheers and no problem! I've only just gotten back to this. 

And that looks like that was the problem, the original datatype is datetime64. For the record (for anyone new to the package who has this issue in future), set use_cftime=True in open_dataset() (xarray version 0.17.0)

I was also curious as to whether you were planning on including the other regression parameters in the calculate_drift() output at some point? I've only had a cursory look at the utils.xr_linregress(), but I can see a use for a standard error and p-value estimate, mainly for inter-model or model-observation comparison.

Thanks again.

**Comment by jbusecke** [comment]
Interesting suggestion @BWBlack. Would you mind opening an issue for that? I think we should more broadly discuss this in the context of an upcoming refactor/extension of the drift_removal capabilities (e.g. #168).
