### ISSUE TITLE
Comparison of multiple datsets

### ISSUE THREAD

**Issue by BenF1998** [jbusecke/cmip6_preprocessing#206]
Hi there,
Thanks for this great package. Apologies if I've missed something in the tutorials (I don't think I have). I wanted to either suggest a new functionality or to know whether there was built in functionality to:

a) generate a CMIP average for a variable, i.e when I import a list of models for a particular variable to the data set, is there a way to plot the average model value for the selected models? 

b) create an anomaly plot for the same variable under two different experiment id's. E.g. Anomaly of SST for 2100 on SSP245 vs 1900 from the historical data for the same model. 

Thanks!

**Comment by jbusecke** [comment]
Hi @BenF1998, thanks for using cmip6_preprocessing. Have a look at my recent [demo at the AMS meeting](https://github.com/jbusecke/presentation_2022_ams_cmip6_cloud/blob/main/ams_2022_cmip6_cloud.ipynb). There I show how to use the tools available to generate the global average sea surface temperature (but this should work with other variables too). Once you have thos time series getting b) should be relatively straightforward.

**Comment by jbusecke** [comment]
Yes, you should be able to just concatenate the individual timeseries (just add them to a list in the loop) into a new xarray dataarray and average over that new dimension.

**Comment by BenF1998** [comment]
Thank you I've managed to do that now!
