### ISSUE TITLE
Upstream dev CI failing during mamba stage

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#230]
The [upstream build](https://github.com/jbusecke/cmip6_preprocessing/runs/6460713102?check_suite_focus=true) is failing, and I am not quite sure I understand why. 

It seems that this happens during the environment setup step, not the testing itself, maybe this is some issue with the github actions themselves or mamba?
For now I will wait and see if this issue resolves itself, but I wanted to tag it here. Maybe someone has seen this happen before and has some tips.

**Comment by dcherian** [comment]
somewhere in your yaml file you need `python: '3.10'` as a string `python: 3.10` gets parsed as `'3.1'`

**Comment by jbusecke** [comment]
Ohhhhhh
