### ISSUE TITLE
Tutorial intake failure

### ISSUE THREAD

**Issue by gjayb** [jbusecke/cmip6_preprocessing#232]
Following the tutorial, the intake.open_esm_datastore(url) is failing:

TypeErrorTraceback (most recent call last)
<ipython-input-39-54ec6c3e2a58> in <module>
      1 url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
----> 2 col = intake.open_esm_datastore(url)

TypeError: 'NoneType' object is not callable

**Comment by dcherian** [comment]
@gjayb can you post the full traceback please

**Comment by gjayb** [comment]
Traceback:
TypeErrorTraceback (most recent call last)
<ipython-input-39-54ec6c3e2a58> in <module>
      1 url = "https://storage.googleapis.com/cmip6/pangeo-cmip6.json"
----> 2 col = intake.open_esm_datastore(url)

TypeError: 'NoneType' object is not callable

I'm running on SciServer. So perhaps the environment is wrong. I'm very new to this, so I'm not totally sure how to check. 
Packages included:
import matplotlib.pyplot as plt
import intake
from intake import open_catalog
import dask
import xarray as xr
import numpy as np
%matplotlib inline
import regionmask
from cmip6_preprocessing.preprocessing import combined_preprocessing

**Comment by jbusecke** [comment]
No worries we can figure this out!

I just tried to get a Sciserver account but failed 5 times and gave up 😭

My suspicion right now is that intake-esm might not be installed?
could you try to enter
```
! conda list
```
in a jupyter cell, and execute it (the `! will execute a shell command`)

**Comment by gjayb** [comment]
That might be it-- I don't see intake at all. What's the right github package to install from?

# packages in environment at /home/idies/miniconda3:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
affine                    2.3.1                    pypi_0    pypi
aiohttp                   3.6.3                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asn1crypto                1.3.0                    py37_0  
async-timeout             3.0.1                    pypi_0    pypi
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     2.2.3                    pypi_0    pypi
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py37h89c1867_1    conda-forge
cf-xarray                 0.7.2                    pypi_0    pypi
cffi                      1.13.2           py37h2e261b9_0  
cftime                    1.6.0                    pypi_0    pypi
chardet                   3.0.4                 py37_1003  
click                     7.1.2                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.7.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cmip6-preprocessing       0.5.1.dev28+g7e75a54          pypi_0    pypi
conda                     4.11.0           py37h89c1867_0    conda-forge
conda-package-handling    1.6.0            py37h7b6447c_0  
cryptography              2.8              py37h1ba5d50_0  
dask                      2.30.0                   pypi_0    pypi
dask-labextension         3.0.0                    pypi_0    pypi
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.30.0                   pypi_0    pypi
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fiona                     1.8.21                   pypi_0    pypi
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
future                    0.18.2                   pypi_0    pypi
geopandas                 0.10.2                   pypi_0    pypi
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_1    conda-forge
gstreamer                 1.14.5               h36ae1b5_1    conda-forge
heapdict                  1.0.1                    pypi_0    pypi
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                      py37_0  
importlib_metadata        1.5.0                    py37_0    conda-forge
inflect                   4.1.0                    py37_0    conda-forge
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.12.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jaraco.itertools          5.0.0                      py_0    conda-forge
jedi                      0.16.0                   py37_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter-server-proxy      1.5.0                    pypi_0    pypi
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyterlab                1.2.6                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libarchive                3.3.3             hc47fbbf_1007    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.71.1               hcdd3856_3    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libsolv                   0.7.16               h8b12597_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.7.3            py37h0ea2b0a_0    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
msgpack                   1.0.0                    pypi_0    pypi
multidict                 4.7.6                    pypi_0    pypi
munch                     2.5.0                    pypi_0    pypi
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1                  he6710b0_1  
nodejs                    10.13.0              he6710b0_0  
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.19.2                   pypi_0    pypi
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.4                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.6.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    8.0.0                    pypi_0    pypi
pint                      0.18                     pypi_0    pypi
pint-xarray               0.2.1                    pypi_0    pypi
pip                       20.0.2                   py37_1  
pooch                     1.6.0                    pypi_0    pypi
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
psutil                    5.7.2                    pypi_0    pypi
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycosat                   0.6.3            py37h7b6447c_0  
pycparser                 2.19                     py37_0  
pygments                  2.5.2                      py_0    conda-forge
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.4.7                    pypi_0    pypi
pyproj                    3.2.1                    pypi_0    pypi
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0  
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2022.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
rasterio                  1.2.10                   pypi_0    pypi
readline                  7.0                  h7b6447c_5  
regionmask                0.9.0                    pypi_0    pypi
reproc                    14.2.1               h36c2ea0_0    conda-forge
reproc-cpp                14.2.1               h58526e2_0    conda-forge
requests                  2.22.0                   py37_1  
ruamel_yaml               0.15.87          py37h7b6447c_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                45.1.0                   py37_0  
shapely                   1.8.2                    pypi_0    pypi
simpervisor               0.3                      pypi_0    pypi
six                       1.14.0                   py37_0  
snuggs                    1.4.7                    pypi_0    pypi
sortedcontainers          2.2.2                    pypi_0    pypi
sqlite                    3.31.1               h7b6447c_0  
tblib                     1.7.0                    pypi_0    pypi
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.8                hbc83047_0  
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.42.0                     py_0  
traitlets                 4.3.3                    py37_0    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.25.8                   py37_0  
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                   py37_0  
widgetsnbextension        3.5.1                    py37_0    conda-forge
xarray                    0.20.2                   pypi_0    pypi
xarrayutils               0.1.4                    pypi_0    pypi
xgcm                      0.6.1                    pypi_0    pypi
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
yarl                      1.5.1                    pypi_0    pypi
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      2.0.0                    pypi_0    pypi
zipp                      2.1.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.4                h3b9ef0a_2    conda-forge

**Comment by dcherian** [comment]
It should've raised `ImportError` when you ran `import intake` in the notebook? 

In any case

```
conda install -c conda-forge intake-esm
```

**Comment by gjayb** [comment]
Notes for anyone else using sciserver: install your packages using pip, not conda (conda hangs for ages, not resolving the environment).
pip install intake-esm
Possibly I chose badly from the available environments for my container. I needed to get pandas too, in the intake-esm dependency download saga that took forever.
Regardless, no I don't get an import error, and no, installing the package didn't help with my particular error.

When I inspect intake, I get that it is a module-
module 'intake' from '/home/idies/miniconda3/envs/Oceanography/lib/python3.8/site-packages/intake/__init__.py'

But intake.open_esm_datastore() is not a program
TypeErrorTraceback (most recent call last)
ipython-input-3-c082cde1bec3 in module
----> 1 intake.open_esm_datastore()
TypeError: 'NoneType' object is not callable

unlike, say, sum()
TypeErrorTraceback (most recent call last)
ipython-input-19-217cace8f485 in module
----> 1 sum()
TypeError: sum() takes at least 1 positional argument (0 given)

Is there another intake-esm call that I can do to check if it got installed?

**Comment by gjayb** [comment]
UPDATE: I got it.
I was starting from an 'oceanography' environment before.
Doing a new notebook starting from a generic py37 worked.
Possibly something had the same name for some reason, who knows.

If anyone has the energy to look through the packages and see what's different, please do. I'll get to it sometime if not.
Packages where it works:

# packages in environment at /home/idies/miniconda3:
 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
affine                    2.3.1                    pypi_0    pypi
aiohttp                   3.6.3                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asn1crypto                1.3.0                    py37_0  
async-timeout             3.0.1                    pypi_0    pypi
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     2.2.3                    pypi_0    pypi
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
certifi                   2021.10.8        py37h89c1867_1    conda-forge
cf-xarray                 0.7.2                    pypi_0    pypi
cffi                      1.13.2           py37h2e261b9_0  
cftime                    1.6.0                    pypi_0    pypi
chardet                   3.0.4                 py37_1003  
charset-normalizer        2.0.12                   pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.7.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cmip6-preprocessing       0.5.1.dev28+g7e75a54          pypi_0    pypi
conda                     4.11.0           py37h89c1867_0    conda-forge
conda-package-handling    1.6.0            py37h7b6447c_0  
cryptography              2.8              py37h1ba5d50_0  
dask                      2.30.0                   pypi_0    pypi
dask-labextension         3.0.0                    pypi_0    pypi
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.30.0                   pypi_0    pypi
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fasteners                 0.17.3                   pypi_0    pypi
fastprogress              1.0.2                    pypi_0    pypi
fiona                     1.8.21                   pypi_0    pypi
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    2022.5.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
geopandas                 0.10.2                   pypi_0    pypi
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_1    conda-forge
gstreamer                 1.14.5               h36ae1b5_1    conda-forge
h5netcdf                  1.0.0                    pypi_0    pypi
h5py                      3.6.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                      py37_0  
importlib_metadata        1.5.0                    py37_0    conda-forge
inflect                   4.1.0                    py37_0    conda-forge
intake                    0.6.5                    pypi_0    pypi
intake-esm                2021.8.17                pypi_0    pypi
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.12.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jaraco.itertools          5.0.0                      py_0    conda-forge
jedi                      0.16.0                   py37_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter-server-proxy      1.5.0                    pypi_0    pypi
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyterlab                1.2.6                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libarchive                3.3.3             hc47fbbf_1007    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.71.1               hcdd3856_3    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libsolv                   0.7.16               h8b12597_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
locket                    1.0.0                    pypi_0    pypi
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.7.3            py37h0ea2b0a_0    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
msgpack                   1.0.0                    pypi_0    pypi
multidict                 4.7.6                    pypi_0    pypi
munch                     2.5.0                    pypi_0    pypi
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1                  he6710b0_1  
netcdf4                   1.5.8                    pypi_0    pypi
nodejs                    10.13.0              he6710b0_0  
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numcodecs                 0.9.1                    pypi_0    pypi
numpy                     1.19.2                   pypi_0    pypi
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.4                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.6.1                      py_0    conda-forge
partd                     1.2.0                    pypi_0    pypi
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    8.0.0                    pypi_0    pypi
pint                      0.18                     pypi_0    pypi
pint-xarray               0.2.1                    pypi_0    pypi
pip                       20.0.2                   py37_1  
pooch                     1.6.0                    pypi_0    pypi
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
psutil                    5.7.2                    pypi_0    pypi
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycosat                   0.6.3            py37h7b6447c_0  
pycparser                 2.19                     py37_0  
pydantic                  1.9.1                    pypi_0    pypi
pygments                  2.5.2                      py_0    conda-forge
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.4.7                    pypi_0    pypi
pyproj                    3.2.1                    pypi_0    pypi
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0  
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2022.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
rasterio                  1.2.10                   pypi_0    pypi
readline                  7.0                  h7b6447c_5  
regionmask                0.9.0                    pypi_0    pypi
reproc                    14.2.1               h36c2ea0_0    conda-forge
reproc-cpp                14.2.1               h58526e2_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
ruamel_yaml               0.15.87          py37h7b6447c_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                45.1.0                   py37_0  
shapely                   1.8.2                    pypi_0    pypi
simpervisor               0.3                      pypi_0    pypi
six                       1.14.0                   py37_0  
snuggs                    1.4.7                    pypi_0    pypi
sortedcontainers          2.2.2                    pypi_0    pypi
sqlite                    3.31.1               h7b6447c_0  
tblib                     1.7.0                    pypi_0    pypi
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.8                hbc83047_0  
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.42.0                     py_0  
traitlets                 4.3.3                    py37_0    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.25.8                   py37_0  
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                   py37_0  
widgetsnbextension        3.5.1                    py37_0    conda-forge
xarray                    0.20.2                   pypi_0    pypi
xarrayutils               0.1.4                    pypi_0    pypi
xgcm                      0.6.1                    pypi_0    pypi
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
yarl                      1.5.1                    pypi_0    pypi
zarr                      2.11.3                   pypi_0    pypi
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      2.0.0                    pypi_0    pypi
zipp                      2.1.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.4                h3b9ef0a_2    conda-forge
