### ISSUE TITLE
Unify variable attributes and units

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#31]
We are currently fixing units if they are in non-standard units (e.g. for depth cm ==> m). 

There are also some inconsistencies in the long names of e.g. dimensions and coordinates. This is a cosmetic issue but I wanted to pin it here. Eventually `combined_preprocessing` should rename all variables in a consistent way.

**Comment by jbusecke** [comment]
I think [pint-xarray](https://github.com/xarray-contrib/pint-xarray) is perfect for doing that. I wonder if anyone here has more experience with pint. E.g. is there a way to convert any unit into the SI unit? I have so far only encountered cases with `cm` as depth unit, but I am wondering if there is a way to do this generally. If not we can add that logic (e.g. provide a mappint dict, but let pint handle the actual conversion).

**Comment by jbusecke** [comment]
cc @TomNicholas

**Comment by TomNicholas** [comment]
Once you import the correct libraries (in this order)
```python
import pint
import cf_xarray.units
import pint_xarray
```
you should be able to add units via `da.pint.quantify()` and convert them via `da.pint.to()`

**Comment by TomNicholas** [comment]
If the units you need aren't present in the registry then they should probably be added in cf-xarray (though you can modify locally too).
