### ISSUE TITLE
combine cmip6_preprocessing with xesmf

### ISSUE THREAD

**Issue by aaronspring** [jbusecke/cmip6_preprocessing#36]
Has anyone used cmip6_pre with xesmf for ocean variables?

with cmip6_pre.__version = 'v0.1.3' I get these coords, lat(x), lon(x) for all models, which cannot be right . this then crashes xesmf.
```
BCC-CSM2-MR CMIP.BCC.BCC-CSM2-MR.esm-piControl.Omon.gn
Coordinates:
    lon        (x) float32 0.5 1.5 2.5 3.5 4.5 ... 355.5 356.5 357.5 358.5 359.5
    lat        (x) float32 0.1662087 0.1662087 0.1662087 ... 0.1662087 0.1662087

**Comment by jbusecke** [comment]
Uhh that looks weird!

I have used xesmf before with cmip6_pre (a much older version), but this looks like a bug. I just fixed a bug in the nominal lon/lay generation (or so I thought) yesterday. That might have introduced this. Does it just happen with this particular model? I don’t even understand how this would be possible.

 I am almost done with a substantial refactor in #35, which might clear this up. This would have some breaking changes, so perhaps it is worth fixing things before?

**Comment by jbusecke** [comment]
>Does it just happen with this particular model?

Sorry I should really wake up before answering these issues 😁 . I am checking on that now.

**Comment by aaronspring** [comment]
that branch https://github.com/aaronspring/LunchBytes_intake-esm_cloud/tree/aaronspring-patch-bokeh on pangeo.binder.io - currently I get unable to connect from pangeo.binder...

**Comment by jbusecke** [comment]
I reproduced the bug and introduced a fix in #37. I will publish a new version right after the tests pass, so that people are less likely to run into this (quite severe) bug. Many thanks for bringing this to attention. 
In the longer run #35 will introduce some better tests and improvements to the nominal lon/lat creation. But I wanted to introduce this fix now.

**Comment by jbusecke** [comment]
Also be aware that I have not unified the various `bounds` used in the models, so the conservative regridding will likely have problems. Would love to work on that in the future.

**Comment by jbusecke** [comment]
Let me know if the newest version fixes your issue and if I can close this. Cheers

**Comment by aaronspring** [comment]
works nicely.
