### ISSUE TITLE
Feature request: xesmf regrid ocean 

### ISSUE THREAD

**Issue by aaronspring** [jbusecke/cmip6_preprocessing#38]
What I think would be very powerful if we could have a demo or module that enables regrading of all different ocean grids to be concatinated into a single xr dataset. 

Often a regridding to 1x1 fails with the default settings. 

Think about cyclic/periodic true false and other fixes that everyone does manually.

**Comment by jbusecke** [comment]
Thanks for raising the issue.
I have not spent a lot of time trying to regrid data. Why does it usually fail?

I think this is somewhat a combined problem with [xgcm](https://github.com/xgcm/xgcm).
In fact I will soon dedicate a good amount of time to enabeling all cmip models with xgcm, which will require some careful treatment of the 'bounds' coordinates. I believe these are also crucial for remapping with xesmf. 
I think this could be a almost a  'freebie' on the way to xgcm compatibility. Ill keep this in mind though.

**Comment by aaronspring** [comment]
> I think this is somewhat a combined problem with xgcm.

Probably. Please tag me once you start with this. Probably we will have a very similar testing and setup algorithm. This isn't a high prio for me - therefore I am happy to wait a bit ;)

> Why does it usually fail?

I wish I'd understand this more. often some rc=506 error message. 
Other problem is that some models have a white line after regridding on the lon=0/180 line. this can probably mostly be handled with `periodic : bool, optional`

**Comment by aaronspring** [comment]
this is an out-of-the-box-test: open ocean data and regrid and plot first timestep. this works for more than a third of all models. I basically get only three different kinds of errors (excluding the AWI model).

```python
variable = "tos"
query = dict(experiment_id="piControl", table_id="Omon", variable_id=variable)
cat = col.search(**query)
cat.df.head()

dset_dict = cat.to_dataset_dict(
    cdf_kwargs={"chunks": {"time": 12 * 50}, "use_cftime": True},
    preprocess=combined_preprocessing,
)
list(dset_dict)

import xesmf as xe

def regrid(ds, deg=1):
    ds_out = xe.util.grid_global(deg, deg)
    regridder = xe.Regridder(ds, ds_out, 'bilinear')
    ds_out = regridder(ds)
    return ds_out
```

```python
models_success=[]
models_fail = []
models_fail_compute = []
for key in dset_dict:
    model = key.split('.')[2]
    print(model)
    ds = dset_dict[key]
    try:
        dsr = regrid(ds)
        try:
            dsr.isel(time=0)[variable].squeeze().plot()
            plt.show()
            models_success.append(model)
        except Exception as e:
            models_fail_compute.append(model)
            print('plotting/loading didnt work because',e)
            print(dsr.coords)
    except Exception as e:
        print(ds.coords)
        print('regridding error',e)
        models_fail.append(model)
    print('\n\n')
print('models_fail: ',models_fail)
print('models_fail_compute: ',models_fail_compute)
print('models_success: ',models_success)
```

results
```
models_fail:  ['CNRM-ESM2-1', 'EC-Earth3-LR', 'CNRM-CM6-1', 'CNRM-CM6-1-HR', 'MRI-ESM2-0', 'NESM3', 'AWI-ESM-1-1-LR', 'MIROC-ES2L', 'IPSL-CM6A-LR', 'MIROC6', 'AWI-CM-1-1-MR', 'NorESM1-F', 'HadGEM3-GC31-MM', 'NorESM2-MM', 'NorESM2-LM', 'MPI-ESM1-2-HR', 'EC-Earth3', 'EC-Earth3-Veg']

models_fail_compute:  ['CNRM-ESM2-1', 'CNRM-CM6-1', 'MRI-ESM2-0', 'GISS-E2-1-G-CC', 'MCM-UA-1-0', 'GISS-E2-2-G', 'CESM2-WACCM', 'CESM2-FV2', 'CESM2-WACCM-FV2', 'CESM2', 'INM-CM4-8', 'GISS-E2-1-H', 'GFDL-ESM4', 'GFDL-CM4', 'INM-CM5-0', 'E3SM-1-1', 'GISS-E2-1-G']

models_success:  ['ACCESS-CM2', 'BCC-CSM2-MR', 'BCC-ESM1', 'CAMS-CSM1-0', 'ACCESS-ESM1-5', 'FGOALS-f3-L', 'NorCPM1', 'HadGEM3-GC31-LL', 'FIO-ESM-2-0', 'CESM2-WACCM', 'CanESM5', 'CIESM', 'CESM2-FV2', 'CESM2-WACCM-FV2', 'CESM2', 'UKESM1-0-LL', 'GFDL-ESM4', 'GFDL-CM4', 'IITM-ESM', 'MPI-ESM-1-2-HAM', 'MPI-ESM1-2-LR', 'SAM0-UNICON']
```

typical errors:
- MRI-ESM2-0:`plotting/loading didnt work because The horizontal shape of input data is (180, 360), different from that ofthe regridder (360, 180)!`
- MIROC-ES2L:`regridding error operand to apply_ufunc has required core dimensions ['x', 'vertex'], but some of these dimensions are absent on an input variable: ['vertex']`
- NESM3: `regridding error ESMC_FieldRegridStoreFile() failed with rc = 506.    Please check the log files (named "*ESMF_LogFile").`

**Comment by jbusecke** [comment]
> MRI-ESM2-0:plotting/loading didnt work because The horizontal shape of input data is (180, 360), different from that ofthe regridder (360, 180)!

Could this be fixed by forcing a `.transpose('x','y', ...)`?

> regridding error operand to apply_ufunc has required core dimensions ['x', 'vertex'], but some of these dimensions are absent on an input variable: ['vertex']

My last PR #40 was a bit half baked, #41 should do away with that (about to run the final tests).

> NESM3: regridding error ESMC_FieldRegridStoreFile() failed with rc = 506. Please check the log files (named "*ESMF_LogFile").

This one sounds like an xesmf problem. Is there something that the models with this have in common? E.g. can you plot their lon fields?

**Comment by aaronspring** [comment]
- `ds = ds.transpose('x','y', ..., transpose_coords=True)` helps
- also #41

**Comment by aaronspring** [comment]
`models_fail:  ['CMIP.CNRM-CERFACS.CNRM-CM6-1.piControl.Omon.gn', 'CMIP.CNRM-CERFACS.CNRM-CM6-1-HR.piControl.Omon.gn', 'CMIP.CNRM-CERFACS.CNRM-ESM2-1.piControl.Omon.gn', 'CMIP.AWI.AWI-ESM-1-1-LR.piControl.Omon.gn', 'CMIP.EC-Earth-Consortium.EC-Earth3-LR.piControl.Omon.gn', 'CMIP.AWI.AWI-CM-1-1-MR.piControl.Omon.gn', 'CMIP.NUIST.NESM3.piControl.Omon.gn', 'CMIP.IPSL.IPSL-CM6A-LR.piControl.Omon.gn', 'CMIP.NCC.NorESM1-F.piControl.Omon.gn', 'CMIP.MOHC.HadGEM3-GC31-MM.piControl.Omon.gn', 'CMIP.NCC.NorESM2-MM.piControl.Omon.gn', 'CMIP.NCC.NorESM2-LM.piControl.Omon.gn', 'CMIP.MPI-M.MPI-ESM1-2-HR.piControl.Omon.gn', 'CMIP.EC-Earth-Consortium.EC-Earth3-Veg.piControl.Omon.gn', 'CMIP.EC-Earth-Consortium.EC-Earth3.piControl.Omon.gn']`

`models_success:  ['CMIP.CNRM-CERFACS.CNRM-CM6-1.piControl.Omon.gr1', 'CMIP.CNRM-CERFACS.CNRM-ESM2-1.piControl.Omon.gr1', 'CMIP.CSIRO-ARCCSS.ACCESS-CM2.piControl.Omon.gn', 'CMIP.BCC.BCC-CSM2-MR.piControl.Omon.gn', 'CMIP.CSIRO.ACCESS-ESM1-5.piControl.Omon.gn', 'CMIP.CAMS.CAMS-CSM1-0.piControl.Omon.gn', 'CMIP.BCC.BCC-ESM1.piControl.Omon.gn', 'CMIP.MRI.MRI-ESM2-0.piControl.Omon.gr', 'CMIP.CAS.FGOALS-f3-L.piControl.Omon.gn', 'CMIP.MRI.MRI-ESM2-0.piControl.Omon.gn', 'CMIP.NASA-GISS.GISS-E2-1-G-CC.piControl.Omon.gn', 'CMIP.NCC.NorCPM1.piControl.Omon.gn', 'CMIP.MOHC.HadGEM3-GC31-LL.piControl.Omon.gn', 'CMIP.MIROC.MIROC-ES2L.piControl.Omon.gn', 'CMIP.FIO-QLNM.FIO-ESM-2-0.piControl.Omon.gn', 'CMIP.UA.MCM-UA-1-0.piControl.Omon.gn', 'CMIP.NCAR.CESM2-WACCM.piControl.Omon.gn', 'CMIP.CCCma.CanESM5.piControl.Omon.gn', 'CMIP.NASA-GISS.GISS-E2-2-G.piControl.Omon.gn', 'CMIP.NCAR.CESM2-WACCM.piControl.Omon.gr', 'CMIP.THU.CIESM.piControl.Omon.gn', 'CMIP.NCAR.CESM2-FV2.piControl.Omon.gn', 'CMIP.NCAR.CESM2-WACCM-FV2.piControl.Omon.gn', 'CMIP.MOHC.UKESM1-0-LL.piControl.Omon.gn', 'CMIP.NCAR.CESM2.piControl.Omon.gn', 'CMIP.NCAR.CESM2-FV2.piControl.Omon.gr', 'CMIP.MIROC.MIROC6.piControl.Omon.gn', 'CMIP.NCAR.CESM2-WACCM-FV2.piControl.Omon.gr', 'CMIP.NCAR.CESM2.piControl.Omon.gr', 'CMIP.INM.INM-CM4-8.piControl.Omon.gr1', 'CMIP.NASA-GISS.GISS-E2-1-H.piControl.Omon.gn', 'CMIP.NOAA-GFDL.GFDL-CM4.piControl.Omon.gn', 'CMIP.NOAA-GFDL.GFDL-ESM4.piControl.Omon.gn', 'CMIP.CCCR-IITM.IITM-ESM.piControl.Omon.gn', 'CMIP.NOAA-GFDL.GFDL-CM4.piControl.Omon.gr', 'CMIP.NOAA-GFDL.GFDL-ESM4.piControl.Omon.gr', 'CMIP.INM.INM-CM5-0.piControl.Omon.gr1', 'CMIP.E3SM-Project.E3SM-1-1.piControl.Omon.gr', 'CMIP.HAMMOZ-Consortium.MPI-ESM-1-2-HAM.piControl.Omon.gn', 'CMIP.NASA-GISS.GISS-E2-1-G.piControl.Omon.gn', 'CMIP.MPI-M.MPI-ESM1-2-LR.piControl.Omon.gn', 'CMIP.SNU.SAM0-UNICON.piControl.Omon.gn']`

always this kind of error: https://github.com/JiaweiZhuang/xESMF/issues/78

https://gitlab.dkrz.de/m300524/lunchbytes_intake-esm/-/blob/523908a9f6da1f748f6557e5dd507b62c3fd452f/tutorial.ipynb

**Comment by aaronspring** [comment]
`ignore_degenerate=True` solves the remain ones.

**Comment by jbusecke** [comment]
Awesome!
