### ISSUE TITLE
cannot import name parse_lon_lat_bounds

### ISSUE THREAD

**Issue by sckw** [jbusecke/cmip6_preprocessing#54]
I am running the single utility function, `parse_lon_lat_bounds` and am running into an import error

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-92-1e894fbe4790> in <module>
----> 1 from cmip6_preprocessing.preprocessing import parse_lon_lat_bounds

ImportError: cannot import name 'parse_lon_lat_bounds' from 'cmip6_preprocessing.preprocessing' (/srv/conda/envs/notebook/lib/python3.7/site-packages/cmip6_preprocessing/preprocessing.py)

```

I came across this trying to go through the [tutorial](https://github.com/jbusecke/cmip6_preprocessing/blob/master/doc/tutorial.ipynb) and started having issues when trying to do the "Consistent CF bounds" section. I did a pip install on pangeo.

**Comment by jbusecke** [comment]
Thanks for reporting this. I think this might be a verion error. Could you install the latest master from github using `pip install git+https://github.com/jbusecke/cmip6_preprocessing.git` and report back if that solves the problem?

**Comment by jbusecke** [comment]
Any luck on this?

**Comment by sckw** [comment]
Aye, that fixed it.... thanks!

**Comment by jbusecke** [comment]
Ill release a new version soon to make sure these changes are included in the conda/pip versions.
