### ISSUE TITLE
Performance issue; preprocessing produces ungodly amount of dask tasks

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#58]
I just discovered a concerning behavior of `combined_preprocessing`, which seems to create a lot more dask tasks for each datasets when I enable the new automatic slicing for large arrays. 

Consider this example:
```python
import intake
import warnings
from cmip6_preprocessing.preprocessing import combined_preprocessing

import dask
dask.config.set(**{'array.slicing.split_large_chunks': True, "array.chunk-size": "256 MiB",})

url = "https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json"
col = intake.open_esm_datastore(url)

cat = col.search(
    table_id='Omon',
    grid_label='gn',
    experiment_id='piControl',
    variable_id='o2',
    source_id=['CanESM5'])
```
Now lets load this single model into a dictionary with and without using `preprocess`

```python
ddict_raw = cat.to_dataset_dict(
                zarr_kwargs={"consolidated": True, "decode_times":False}, 
            )
ddict_raw['CMIP.CCCma.CanESM5.piControl.Omon.gn'].o2.data
```
![image](https://user-images.githubusercontent.com/14314623/96305601-24cb9980-0fcc-11eb-8f8d-3c6c19556d16.jpeg)

```python
ddict = cat.to_dataset_dict(
                zarr_kwargs={"consolidated": True, "decode_times":False},
                preprocess=combined_preprocessing
            )
ddict['CMIP.CCCma.CanESM5.piControl.Omon.gn'].o2.data
```
![image](https://user-images.githubusercontent.com/14314623/96305629-314ff200-0fcc-11eb-8743-65821a6c43d0.jpeg)

The tasks increased from ~30k to **more than 9 million!**. This seems to hit the limit of what dask can handle. 

I dug a little deeper and it seems that the increase is happening during [this step ](https://github.com/jbusecke/cmip6_preprocessing/blob/72a3734c4c29c43efcf92ec5196a4ab4ee2a431c/cmip6_preprocessing/preprocessing.py#L406), specifically the call to `.sortby('x)` [here](https://github.com/jbusecke/cmip6_preprocessing/blob/72a3734c4c29c43efcf92ec5196a4ab4ee2a431c/cmip6_preprocessing/preprocessing.py#L147).

If I deactivate the new automatic slicing for large arrays I get this

```python
import dask
with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ddict_test = cat.to_dataset_dict(
                zarr_kwargs={"consolidated": True, "decode_times":False},
                preprocess=combined_preprocessing
            )
ddict_test['CMIP.CCCma.CanESM5.piControl.Omon.gn'].o2.data
```
![image](https://user-images.githubusercontent.com/14314623/96306133-15008500-0fcd-11eb-8a3a-9c9c82a3b905.jpeg)

This prevents the `x` dimension to be rechunked to single values chunks.

Unfortunately I dont understand enough about these xarray/dask internals. @dcherian is this something that you know more about? Ill try to come up with a more simplified example and crosspost over at xarray. Just wanted to document this behavior here first.

**Comment by jbusecke** [comment]
Seems like this is related: https://github.com/pydata/xarray/issues/4428

Should i deactivate the auto slicing for the whole `combined_preprocessing`? Or is there a more dask friendly way to sort values along a dimension (in this case it is not chunked, I got a local version where it is chunked...that causes even more trouble...

I am also unclear why these chunks are split in the first place? They are smaller than `dask.config.get('array.chunk-size')`, which is `128MB`. Is there an internal step that creates larger chunks as the one in the input/output?

**Comment by dcherian** [comment]
>  Is there an internal step that creates larger chunks as the one in the input/output?

`sort` becomes an `isel` which triggers that behaviour. But clearly your chunks are becoming too small. Can you produce a minimal example?

**Comment by jbusecke** [comment]
Working on it. Do you think that is better posted over at xarray or here?

**Comment by jbusecke** [comment]
I think I got a simpler example with the same issue:

```python
import xarray as xr
import numpy as np

import dask
dask.config.set(**{'array.slicing.split_large_chunks': True,
                   "array.chunk-size": "24 MiB",})

da = xr.DataArray(np.random.rand(10), dims=['x'],
                  coords={'x':[3,4,5,6,7,9,8,0,2,1]}).chunk({'x':-1}).expand_dims(y=1000, time=2000).chunk({'y':-1, 'time':200})
da
```
![image](https://user-images.githubusercontent.com/14314623/96308854-1bddc680-0fd2-11eb-96d9-5ab4a46414ea.jpeg)

Note that I set the array chunk size to be larger than the chunks of the array.

If I now sort it by `x`, I get much smaller chunks:
```python
da.sortby('x')
```
![image](https://user-images.githubusercontent.com/14314623/96308877-28621f00-0fd2-11eb-83d6-c32a99f31084.jpeg)

If I deactivate the auto slicing, I get the expected result (+ a few tasks but not 3x as much):
```python
with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    da_sorted = da.sortby('x')
da_sorted
```

![image](https://user-images.githubusercontent.com/14314623/96308969-56dffa00-0fd2-11eb-97d0-9a5928e400e3.jpeg)


I dont know enough about these internals but that seems unintuitive to me.

**Comment by jbusecke** [comment]
I have changed the array size to `dask.config.set(**{'array.slicing.split_large_chunks': True, "array.chunk-size": "128 GB",})` and the problem goes away 🤣. Still feel that this value should be more representative of what the chunks actually end up being...

**Comment by aaronspring** [comment]
another option to circumvent this: use `cmip6_preprocessing` after using `intake-esm` and not via `preprocess` in `intake-esm`

**Comment by jbusecke** [comment]
You mean with `aggregate=False`, @aaronspring ?

**Comment by aaronspring** [comment]
> You mean with `aggregate=False`, @aaronspring ?

maybe. I usually dont use aggregate. I just meant to use the functions from your package after intake-esm on xarray objects directly.

**Comment by jbusecke** [comment]
I am experimenting with this and will report back. This is a good suggestion and maybe it should become our default recommendation so that people are not bound to intake-esm, but can still use it if desired.

**Comment by aaronspring** [comment]
The functions works as expected on datasets. When used on extracted dataarrays, the missing attrs may cause some functions to fail

**Comment by jbusecke** [comment]
I have updated the recommended workflow to use `aggregate=False` [here](https://cmip6-preprocessing.readthedocs.io/en/latest/#suggested-workflow), which should avoid this problem. Closing this.
