### ISSUE TITLE
Sorting longitudes produces many chunks

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#75]
[These](https://github.com/jbusecke/cmip6_preprocessing/blob/8cdd02de9fa35b373be5a66da9bc481ca3a6aaa8/cmip6_preprocessing/preprocessing.py#L147-L149) lines do not work nicely with the auto-chunking (see #58). 

@dcherian mentioned that it might be more efficient to separate the array in only two arrays and then shuffle those around. This seems like a promising step to try. 

The other way of dealing with it (which is what I am currently doing), is to omit that step alltoghether and execute that step at the end of a workflow, where the dimensionality has been reduced (e.g. for plotting).

**Comment by dcherian** [comment]
I wonder if `xr.concat(ds.sel(longitude=slice(0, 180)), ds.sel(longitude=slice(-180,0), dim="longitude")` so that the indexer has "structure" which may be more efficient?

**Comment by jbusecke** [comment]
Ill give that a go in the next days. Would be nice to not break the way that output is created.

**Comment by jbusecke** [comment]
I'll try to implement this in a few. Quick question: I remember some of the models also needed a flip in the y direction (Lats were not increasing along the dimension). Is there a dass friendly way of achieving this in xarray?

**Comment by dcherian** [comment]
i think that's ok but we should check.
