### ISSUE TITLE
The pangeo-cmip6.json url should be updated

### ISSUE THREAD

**Issue by naomi-henderson** [jbusecke/cmip6_preprocessing#80]
The current implementation points to the old intake_esm/json file here:
   https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json
but really should be updated to:
   https://cmip6.storage.googleapis.com/pangeo-cmip6.json

The current differences are not very important for cmip6_preprocessing, but as we change the way we deal with dataset versions, see this [issue](https://github.com/pangeo-forge/cmip6-pipeline/issues/12), I would like to be able to update the json, if needed. 

Thanks!  (Yes, I know I could do a pull request - but it will be much more quicker (and reliable) if @jbusecke does it!)

**Comment by jbusecke** [comment]
😱 Oh my, yes lets fix that pronto.

**Comment by jbusecke** [comment]
Thanks for checking this @naomi-henderson, I had been using the old file in a lot of instances (yikes).

**Comment by jbusecke** [comment]
Closed via #81
