### ISSUE TITLE
Testing catalog producing a bunch of failures

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#90]
@naomi-henderson, I just noticed a bunch of failures in the [large archive sweep](https://github.com/jbusecke/cmip6_preprocessing/actions/runs/555329032) and so far all failures seem to be associated with the testing catalog. Just wanted to alert you of that.

**Comment by naomi-henderson** [comment]
@jbusecke , the restructuring of the bucket is complete and the testing catalog is obsolete - I have not yet deleted the `-testing` objects and am now removing the old store names. You should now be using `https://storage.googleapis.com/cmip6/pangeo-cmip6.json`, as before. 

Sorry for the confusion.  I will delete the testing catalog files now.

**Comment by jbusecke** [comment]
Thanks for confirming. I figured that stuff is in flux right now. Glad we could check the two against each other!

**Comment by naomi-henderson** [comment]
Yes, good to know that we are on the same page.  

Did you see that I have added a paragraph on cmip6_preprocessing to the documentation on [pangeo-data](https://pangeo-data.github.io/pangeo-cmip6-cloud/accessing_data.html#preprocessing-the-cmip6-datasets)?  You might want to check it out and see if you want to elaborate on usage

**Comment by jbusecke** [comment]
This is so great! Thank you very much! I will put in an issue to check back with this once I refactor stuff for v0.2.0. But for now this is exactly the recommended way to do it.

**Comment by jbusecke** [comment]
I have removed the testing catalog in #97. Closing this now
